name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'  # This matches all pull requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.19.2]
    steps:
     # Checkout code with ref: ensure we are using the latest commit hash
      - name: Checkout code
        uses: actions/checkout@v4  # Use the updated checkout action
        with:
          ref: ${{ github.sha }}  # Ensure the latest commit hash is used

      # Setup Node.js 18 explicitly with setup-node
      - name: Set up Node.js
        uses: actions/setup-node@v4  # Node.js setup
        with:
          node-version: ${{ matrix.node-version }} # Ensure Node 18 is used
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --verbose  # Run npm install with verbose output for debugging

      # Build project
      - name: Build
        run: npm run build --verbose  # Run build with verbose output to debug issues

      # TypeScript type check
      - name: TypeScript type check
        run: npm run type-check

      # Lint code
      - name: Lint
        run: npm run lint

      # Fix lint issues
      - name: Lint fix
        run: npm run lint:fix

      # Format code
      - name: Format
        run: npm run format

      # Check formatting
      - name: Format check
        run: npm run format:check

      # Run tests
      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4  # Use the updated checkout action

      # Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install production dependencies
      - name: Install production dependencies
        run: npm ci --production  # Install only production dependencies

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-cicd:latest
          push: true