name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Set Node.js 24 for your workflow
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure the latest version (v4, if available)
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24  # Ensure the latest version (v6, if available)
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run lint
        run: npm run lint
      
      - name: Build
        run: npm run build
      
      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm run test

      - name: Run lint staged
        run: npm run lint-staged